=== I3artek/OOD_XML/Garden/GardenLibrary/garden.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="garden"
           targetNamespace="garden">
    <xs:element name="garden" type="gardenType">
        <xs:key name="color" id="color">
            <xs:selector xpath="color"/>
            <xs:field xpath="@name"/>
        </xs:key>
    </xs:element>
    <xs:attributeGroup name="plants_and_insects">
        <xs:attribute name="latinName">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z][^ ]* .*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="color"/>
    </xs:attributeGroup>
    <xs:simpleType name="monthType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="January"/>
            <xs:enumeration value="March"/>
            <xs:enumeration value="April"/>
            <xs:enumeration value="May"/>
            <xs:enumeration value="June"/>
            <xs:enumeration value="July"/>
            <xs:enumeration value="August"/>
            <xs:enumeration value="September"/>
            <xs:enumeration value="October"/>
            <xs:enumeration value="November"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="color_value">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="1" />
            <xs:minInclusive value="0.0" />
            <xs:maxInclusive value="1.0" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="colorType">
        <xs:sequence>
            <xs:element name="red" type="color_value">
            </xs:element>
            <xs:element name="green" type="color_value">
            </xs:element>
            <xs:element name="blue" type="color_value">
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="plantType">
        <xs:sequence>
            <xs:element type="monthType" name="month" maxOccurs="unbounded" minOccurs="1">
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="plants_and_insects"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="insectType">
        <xs:sequence>
            <xs:element type="monthType" name="month" maxOccurs="unbounded" minOccurs="1">
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="plants_and_insects"/>
        <xs:attribute type="xs:string" name="id" use="required"/>
    </xs:complexType>
    <xs:complexType name="gardenType">
        <xs:sequence>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element type="colorType" name="color" maxOccurs="unbounded" minOccurs="0"/>
                    <xs:element type="plantType" name="plant" maxOccurs="unbounded" minOccurs="0"/>
                </xs:choice>
            </xs:sequence>
            <xs:sequence>
                <xs:element type="insectType" name="insect" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== I3artek/OOD_XML/Garden/garden.xml
<?xml version="1.0" encoding="utf-8"?>
<garden xmlns="garden"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="garden garden.xsd">
  <color name="green">
    <red>0.1</red><green>1.0</green><blue>0.0</blue>
  </color>
  <color name="red">
    <red>1.0</red><green>0.1</green><blue>0.1</blue>
  </color>
  <plant latinName="Ribes spicatum Robson" name="currant" color="red">
    <month>June</month>
    <month>July</month>
  </plant>
  <plant latinName="Phaseolus vulgaris" name="bean" color="green">
    <month>August</month>
  </plant>
  <color name="brown">
    <red>1.0</red><green>0.8</green><blue>0.1</blue>
  </color>
  <plant latinName="Solanum lycopersicum" name="tomato" color="red">
    <month>August</month>
  </plant>
  <insect latinName="Lampronia capitella" color="brown" id="lc">
    <month>May</month>
    <month>June</month>
  </insect>
  <insect latinName="Trialeurodes vaporariorum" color="green" id="tv">
    <month>April</month>
    <month>May</month>
    <month>June</month>
    <month>July</month>
  </insect>
  <insect latinName="Locusta migratoria" color="brown" id="lm">
    <month>May</month>
    <month>June</month>
    <month>July</month>
  </insect>
</garden>
